name: apptest
description: "A new Flutter project."

version: 1.0.1+2

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  flutter_gen: ^5.11.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  go_router: ^16.2.1
  flutter_native_splash: ^2.4.6
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  flutter_gen_runner: ^5.11.0


flutter_gen:
  output: lib/gen/
  line_length: 80 

  colors:
    inputs:
      - assets/colors/colors.xml
  # Optional
  integrations:
    image: true
    flutter_svg: true 


flutter:


  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
